package com.ucentral.software.ui;

import com.ucentral.software.service.ManagerService;

public class PanelDashboard extends javax.swing.JPanel {

    private final Main container;

    private final ManagerService service;

    /**
     * Creates new form Dashboard
     */
    public PanelDashboard(Main container, ManagerService service) {
        this.container = container;
        this.service = service;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        info = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        selectedCreditCard = new javax.swing.JComboBox<>();
        quotaLabel = new javax.swing.JLabel();
        debtLabel = new javax.swing.JLabel();
        quotaField = new javax.swing.JLabel();
        debtField = new javax.swing.JLabel();
        ccLabel5 = new javax.swing.JLabel();
        transactionsPanel = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        endDateLabel = new javax.swing.JLabel();
        endDateField = new javax.swing.JTextField();
        purchasesPanel = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        logOutButton1 = new javax.swing.JButton();
        startDateLabel1 = new javax.swing.JLabel();
        startDateField1 = new javax.swing.JTextField();
        startDateLabel2 = new javax.swing.JLabel();
        startDateField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        startDateLabel3 = new javax.swing.JLabel();
        paymentsPanel = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        logOutButton2 = new javax.swing.JButton();
        startDateLabel4 = new javax.swing.JLabel();
        startDateField3 = new javax.swing.JTextField();
        startDateLabel5 = new javax.swing.JLabel();
        startDateField4 = new javax.swing.JTextField();
        applicationPanel = new javax.swing.JPanel();
        applyLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 400));

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setPreferredSize(new java.awt.Dimension(600, 400));

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(22, 22, 22));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Tarjeta de crédito");

        logOutButton.setBackground(new java.awt.Color(0, 204, 204));
        logOutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("logOut");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        selectedCreditCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectedCreditCard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectedCreditCardItemStateChanged(evt);
            }
        });

        quotaLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        quotaLabel.setForeground(new java.awt.Color(22, 22, 22));
        quotaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quotaLabel.setText("Cupo");

        debtLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        debtLabel.setForeground(new java.awt.Color(22, 22, 22));
        debtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debtLabel.setText("Deuda a la fecha");

        quotaField.setBackground(new java.awt.Color(255, 255, 255));
        quotaField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quotaField.setForeground(new java.awt.Color(22, 22, 22));
        quotaField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quotaField.setText("0");

        debtField.setBackground(new java.awt.Color(255, 255, 255));
        debtField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        debtField.setForeground(new java.awt.Color(22, 22, 22));
        debtField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debtField.setText("0");

        ccLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ccLabel5.setForeground(new java.awt.Color(22, 22, 22));
        ccLabel5.setText("Seleccione un producto");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addComponent(ccLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quotaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(debtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(quotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quotaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(debtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPane.addTab("info", info);

        transactionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        transactionsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        title2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title2.setForeground(new java.awt.Color(22, 22, 22));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Tarjeta de crédito");

        startDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel.setText("fecha inicio");

        startDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateField.setForeground(new java.awt.Color(22, 22, 22));

        endDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        endDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        endDateLabel.setForeground(new java.awt.Color(22, 22, 22));
        endDateLabel.setText("fecha fin");

        endDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        endDateField.setForeground(new java.awt.Color(22, 22, 22));

        javax.swing.GroupLayout transactionsPanelLayout = new javax.swing.GroupLayout(transactionsPanel);
        transactionsPanel.setLayout(transactionsPanelLayout);
        transactionsPanelLayout.setHorizontalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        transactionsPanelLayout.setVerticalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        tabbedPane.addTab("transactions", transactionsPanel);

        purchasesPanel.setBackground(new java.awt.Color(255, 255, 255));
        purchasesPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        title3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title3.setForeground(new java.awt.Color(22, 22, 22));
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Tarjeta de crédito");

        logOutButton1.setBackground(new java.awt.Color(0, 204, 204));
        logOutButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logOutButton1.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton1.setText("guardar");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        startDateLabel1.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel1.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel1.setText("fecha ");

        startDateField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateField1.setForeground(new java.awt.Color(22, 22, 22));

        startDateLabel2.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel2.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel2.setText("precio");

        startDateField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateField2.setForeground(new java.awt.Color(22, 22, 22));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        startDateLabel3.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel3.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel3.setText("descripcion");

        javax.swing.GroupLayout purchasesPanelLayout = new javax.swing.GroupLayout(purchasesPanel);
        purchasesPanel.setLayout(purchasesPanelLayout);
        purchasesPanelLayout.setHorizontalGroup(
            purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchasesPanelLayout.createSequentialGroup()
                        .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(startDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(startDateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(purchasesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logOutButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchasesPanelLayout.createSequentialGroup()
                        .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(title3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(startDateLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        purchasesPanelLayout.setVerticalGroup(
            purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasesPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purchasesPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(startDateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPane.addTab("purchases", purchasesPanel);

        paymentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        paymentsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        title4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title4.setForeground(new java.awt.Color(22, 22, 22));
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Tarjeta de crédito");

        logOutButton2.setBackground(new java.awt.Color(0, 204, 204));
        logOutButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logOutButton2.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton2.setText("guardar");
        logOutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton2ActionPerformed(evt);
            }
        });

        startDateLabel4.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel4.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel4.setText("fecha ");

        startDateField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateField3.setForeground(new java.awt.Color(22, 22, 22));

        startDateLabel5.setBackground(new java.awt.Color(255, 255, 255));
        startDateLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        startDateLabel5.setForeground(new java.awt.Color(22, 22, 22));
        startDateLabel5.setText("precio");

        startDateField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateField4.setForeground(new java.awt.Color(22, 22, 22));

        javax.swing.GroupLayout paymentsPanelLayout = new javax.swing.GroupLayout(paymentsPanel);
        paymentsPanel.setLayout(paymentsPanelLayout);
        paymentsPanelLayout.setHorizontalGroup(
            paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentsPanelLayout.createSequentialGroup()
                .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paymentsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(startDateField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(startDateLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paymentsPanelLayout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logOutButton2))))
                .addGap(20, 20, 20))
        );
        paymentsPanelLayout.setVerticalGroup(
            paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentsPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentsPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(logOutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPane.addTab("payments", paymentsPanel);

        applicationPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        applyLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        applyLabel.setForeground(new java.awt.Color(22, 22, 22));
        applyLabel.setText("Solicitar nuevo producto");

        applyButton.setText("solicitar");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        title1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title1.setForeground(new java.awt.Color(22, 22, 22));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Tarjeta de crédito");

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(applicationPanelLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(200, Short.MAX_VALUE)))
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(applicationPanelLayout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(applyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        tabbedPane.addTab("application", applicationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        service.creditCardApplication();
        enableApplyButton();
        refreshData();
        fillComboBox();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        logOut();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void selectedCreditCardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectedCreditCardItemStateChanged
        onComboBoxChange();
    }//GEN-LAST:event_selectedCreditCardItemStateChanged

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void logOutButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButton2ActionPerformed

    public void init() {
        clearFileds();
        refreshData();
        fillComboBox();
        enableApplyButton();
    }

    private void clearFileds() {
        debtField.setText("0");
        quotaField.setText("0");
        applyButton.setEnabled(Boolean.TRUE);
        selectedCreditCard.setEnabled(Boolean.TRUE);
    }

    private void refreshData() {
        service.account();
    }

    private void fillComboBox() {

        selectedCreditCard.removeAllItems();
        var cards = service.getCreditCards();

        if (cards.isEmpty()) {
            selectedCreditCard.setEnabled(Boolean.FALSE);
            return;
        }

        cards.forEach(card -> {
            selectedCreditCard.addItem(card.getNumber());
        });

        selectedCreditCard.setEnabled(Boolean.TRUE);

    }

    private void enableApplyButton() {

        var cards = service.getCreditCards();
        Boolean isEnable = cards.isEmpty() || cards.size() < 3;
        applyButton.setEnabled(isEnable);

    }

    private void onComboBoxChange() {

        var numberCard = selectedCreditCard.getSelectedItem();

        if (numberCard == null) {
            return;
        }

        service.setSelectedCreditCard(numberCard.toString());

        var card = service.getCreditCard();
        quotaField.setText(card.getBalance().toString());
        debtField.setText(card.getDebt().toString());

    }

    private void logOut() {
        service.logOut();
        container.showLoginPanel();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel applyLabel;
    private javax.swing.JLabel ccLabel5;
    private javax.swing.JLabel debtField;
    private javax.swing.JLabel debtLabel;
    private javax.swing.JTextField endDateField;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JPanel info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JButton logOutButton2;
    private javax.swing.JPanel paymentsPanel;
    private javax.swing.JPanel purchasesPanel;
    private javax.swing.JLabel quotaField;
    private javax.swing.JLabel quotaLabel;
    private javax.swing.JComboBox<String> selectedCreditCard;
    private javax.swing.JTextField startDateField;
    private javax.swing.JTextField startDateField1;
    private javax.swing.JTextField startDateField2;
    private javax.swing.JTextField startDateField3;
    private javax.swing.JTextField startDateField4;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel startDateLabel1;
    private javax.swing.JLabel startDateLabel2;
    private javax.swing.JLabel startDateLabel3;
    private javax.swing.JLabel startDateLabel4;
    private javax.swing.JLabel startDateLabel5;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JPanel transactionsPanel;
    // End of variables declaration//GEN-END:variables

}
