package com.ucentral.software.ui;

import com.ucentral.software.model.Transaction;
import com.ucentral.software.service.ManagerService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;

public class PanelDashboard extends javax.swing.JPanel {

  private final Main container;

  private final ManagerService service;

  private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

  /**
   * Creates new form Dashboard
   */
  public PanelDashboard(Main container, ManagerService service) {
    this.container = container;
    this.service = service;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabbedPane = new javax.swing.JTabbedPane();
    info = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    logOutButton = new javax.swing.JButton();
    selectedCreditCard = new javax.swing.JComboBox<>();
    quotaLabel = new javax.swing.JLabel();
    debtLabel = new javax.swing.JLabel();
    quotaField = new javax.swing.JLabel();
    debtField = new javax.swing.JLabel();
    ccLabel5 = new javax.swing.JLabel();
    transactionsPanel = new javax.swing.JPanel();
    transactionsButton = new javax.swing.JButton();
    title2 = new javax.swing.JLabel();
    transactionsStartDateLabel = new javax.swing.JLabel();
    transactionsStartDateField = new javax.swing.JTextField();
    transactionsEndDateLabel = new javax.swing.JLabel();
    transactionsEndDateField = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    transactionsTextArea = new javax.swing.JTextArea();
    purchasesPanel = new javax.swing.JPanel();
    title3 = new javax.swing.JLabel();
    savePurchaseButton = new javax.swing.JButton();
    purchaseDateLabel = new javax.swing.JLabel();
    purchaseDateField = new javax.swing.JTextField();
    purchasePriceLabel = new javax.swing.JLabel();
    purchasePriceField = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    purchaseTextArea = new javax.swing.JTextArea();
    purchaseDescriptionLabel = new javax.swing.JLabel();
    paymentsPanel = new javax.swing.JPanel();
    title4 = new javax.swing.JLabel();
    paymentButton = new javax.swing.JButton();
    paymentDateLabel = new javax.swing.JLabel();
    paymentDateField = new javax.swing.JTextField();
    paymentPriceLabel = new javax.swing.JLabel();
    paymentPriceField = new javax.swing.JTextField();
    applicationPanel = new javax.swing.JPanel();
    applyLabel = new javax.swing.JLabel();
    applyButton = new javax.swing.JButton();
    title1 = new javax.swing.JLabel();

    setMinimumSize(new java.awt.Dimension(600, 400));

    info.setBackground(new java.awt.Color(255, 255, 255));
    info.setPreferredSize(new java.awt.Dimension(600, 400));

    title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    title.setForeground(new java.awt.Color(22, 22, 22));
    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setText("credit card");

    logOutButton.setBackground(new java.awt.Color(0, 204, 204));
    logOutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    logOutButton.setForeground(new java.awt.Color(255, 255, 255));
    logOutButton.setText("log out");
    logOutButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logOutButtonActionPerformed(evt);
      }
    });

    selectedCreditCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    selectedCreditCard.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        selectedCreditCardItemStateChanged(evt);
      }
    });

    quotaLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    quotaLabel.setForeground(new java.awt.Color(22, 22, 22));
    quotaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    quotaLabel.setText("Quota");

    debtLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    debtLabel.setForeground(new java.awt.Color(22, 22, 22));
    debtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    debtLabel.setText("Debt to date");

    quotaField.setBackground(new java.awt.Color(255, 255, 255));
    quotaField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    quotaField.setForeground(new java.awt.Color(22, 22, 22));
    quotaField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    quotaField.setText("0");

    debtField.setBackground(new java.awt.Color(255, 255, 255));
    debtField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    debtField.setForeground(new java.awt.Color(22, 22, 22));
    debtField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    debtField.setText("0");

    ccLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    ccLabel5.setForeground(new java.awt.Color(22, 22, 22));
    ccLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ccLabel5.setText("Select product");

    javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
    info.setLayout(infoLayout);
    infoLayout.setHorizontalGroup(
      infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(selectedCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(160, 160, 160))
      .addGroup(infoLayout.createSequentialGroup()
        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(logOutButton)
          .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
              .addGap(75, 75, 75)
              .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(quotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(quotaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGap(50, 50, 50)
              .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(debtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(debtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(infoLayout.createSequentialGroup()
              .addGap(193, 193, 193)
              .addComponent(ccLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(infoLayout.createSequentialGroup()
              .addGap(20, 20, 20)
              .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(33, Short.MAX_VALUE))
    );
    infoLayout.setVerticalGroup(
      infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(infoLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(61, 61, 61)
        .addComponent(ccLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectedCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40)
        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(infoLayout.createSequentialGroup()
            .addComponent(quotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(quotaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(infoLayout.createSequentialGroup()
            .addComponent(debtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(debtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(33, 33, 33)
        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(60, 60, 60))
    );

    tabbedPane.addTab("info", info);

    transactionsPanel.setBackground(new java.awt.Color(255, 255, 255));
    transactionsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

    transactionsButton.setBackground(new java.awt.Color(0, 204, 204));
    transactionsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    transactionsButton.setForeground(new java.awt.Color(255, 255, 255));
    transactionsButton.setText("find");
    transactionsButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        transactionsButtonActionPerformed(evt);
      }
    });

    title2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    title2.setForeground(new java.awt.Color(22, 22, 22));
    title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title2.setText("credit card");

    transactionsStartDateLabel.setBackground(new java.awt.Color(255, 255, 255));
    transactionsStartDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    transactionsStartDateLabel.setForeground(new java.awt.Color(22, 22, 22));
    transactionsStartDateLabel.setText("start date");

    transactionsStartDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    transactionsStartDateField.setForeground(new java.awt.Color(22, 22, 22));

    transactionsEndDateLabel.setBackground(new java.awt.Color(255, 255, 255));
    transactionsEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    transactionsEndDateLabel.setForeground(new java.awt.Color(22, 22, 22));
    transactionsEndDateLabel.setText("end date");

    transactionsEndDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    transactionsEndDateField.setForeground(new java.awt.Color(22, 22, 22));

    transactionsTextArea.setEditable(false);
    transactionsTextArea.setColumns(20);
    transactionsTextArea.setRows(5);
    jScrollPane2.setViewportView(transactionsTextArea);

    javax.swing.GroupLayout transactionsPanelLayout = new javax.swing.GroupLayout(transactionsPanel);
    transactionsPanel.setLayout(transactionsPanelLayout);
    transactionsPanelLayout.setHorizontalGroup(
      transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(transactionsPanelLayout.createSequentialGroup()
        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(transactionsEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(transactionsEndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(transactionsPanelLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(transactionsStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(transactionsStartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(34, Short.MAX_VALUE))
    );
    transactionsPanelLayout.setVerticalGroup(
      transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(transactionsPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(transactionsPanelLayout.createSequentialGroup()
            .addComponent(transactionsStartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(transactionsStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(transactionsPanelLayout.createSequentialGroup()
            .addComponent(transactionsEndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(transactionsEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(50, Short.MAX_VALUE))
    );

    tabbedPane.addTab("transactions", transactionsPanel);

    purchasesPanel.setBackground(new java.awt.Color(255, 255, 255));
    purchasesPanel.setPreferredSize(new java.awt.Dimension(600, 400));

    title3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    title3.setForeground(new java.awt.Color(22, 22, 22));
    title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title3.setText("credit card");

    savePurchaseButton.setBackground(new java.awt.Color(0, 204, 204));
    savePurchaseButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    savePurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
    savePurchaseButton.setText("save");
    savePurchaseButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        savePurchaseButtonActionPerformed(evt);
      }
    });

    purchaseDateLabel.setBackground(new java.awt.Color(255, 255, 255));
    purchaseDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    purchaseDateLabel.setForeground(new java.awt.Color(22, 22, 22));
    purchaseDateLabel.setText("date");

    purchaseDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    purchaseDateField.setForeground(new java.awt.Color(22, 22, 22));

    purchasePriceLabel.setBackground(new java.awt.Color(255, 255, 255));
    purchasePriceLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    purchasePriceLabel.setForeground(new java.awt.Color(22, 22, 22));
    purchasePriceLabel.setText("price");

    purchasePriceField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    purchasePriceField.setForeground(new java.awt.Color(22, 22, 22));

    purchaseTextArea.setColumns(20);
    purchaseTextArea.setRows(5);
    jScrollPane1.setViewportView(purchaseTextArea);

    purchaseDescriptionLabel.setBackground(new java.awt.Color(255, 255, 255));
    purchaseDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    purchaseDescriptionLabel.setForeground(new java.awt.Color(22, 22, 22));
    purchaseDescriptionLabel.setText("description");

    javax.swing.GroupLayout purchasesPanelLayout = new javax.swing.GroupLayout(purchasesPanel);
    purchasesPanel.setLayout(purchasesPanelLayout);
    purchasesPanelLayout.setHorizontalGroup(
      purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasesPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchasesPanelLayout.createSequentialGroup()
            .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(purchaseDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(purchaseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(purchasePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(purchasePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchasesPanelLayout.createSequentialGroup()
            .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(savePurchaseButton)
              .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(title3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(purchaseDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 33, Short.MAX_VALUE))))
    );
    purchasesPanelLayout.setVerticalGroup(
      purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(purchasesPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(purchasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(purchasesPanelLayout.createSequentialGroup()
            .addComponent(purchaseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(purchaseDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(purchasesPanelLayout.createSequentialGroup()
            .addComponent(purchasePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(purchasePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addComponent(purchaseDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(37, 37, 37)
        .addComponent(savePurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(48, 48, 48))
    );

    tabbedPane.addTab("purchases", purchasesPanel);

    paymentsPanel.setBackground(new java.awt.Color(255, 255, 255));
    paymentsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

    title4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    title4.setForeground(new java.awt.Color(22, 22, 22));
    title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title4.setText("credit card");

    paymentButton.setBackground(new java.awt.Color(0, 204, 204));
    paymentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    paymentButton.setForeground(new java.awt.Color(255, 255, 255));
    paymentButton.setText("save");
    paymentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        paymentButtonActionPerformed(evt);
      }
    });

    paymentDateLabel.setBackground(new java.awt.Color(255, 255, 255));
    paymentDateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    paymentDateLabel.setForeground(new java.awt.Color(22, 22, 22));
    paymentDateLabel.setText("date");

    paymentDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    paymentDateField.setForeground(new java.awt.Color(22, 22, 22));

    paymentPriceLabel.setBackground(new java.awt.Color(255, 255, 255));
    paymentPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    paymentPriceLabel.setForeground(new java.awt.Color(22, 22, 22));
    paymentPriceLabel.setText("price");

    paymentPriceField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    paymentPriceField.setForeground(new java.awt.Color(22, 22, 22));

    javax.swing.GroupLayout paymentsPanelLayout = new javax.swing.GroupLayout(paymentsPanel);
    paymentsPanel.setLayout(paymentsPanelLayout);
    paymentsPanelLayout.setHorizontalGroup(
      paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(paymentsPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentsPanelLayout.createSequentialGroup()
            .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(paymentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(paymentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(paymentPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(paymentPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(171, 171, 171))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentsPanelLayout.createSequentialGroup()
            .addGroup(paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(paymentButton)
              .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(33, Short.MAX_VALUE))))
    );
    paymentsPanelLayout.setVerticalGroup(
      paymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(paymentsPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
        .addComponent(paymentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(paymentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(paymentPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(paymentPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(42, 42, 42)
        .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(48, 48, 48))
    );

    tabbedPane.addTab("payments", paymentsPanel);

    applicationPanel.setBackground(new java.awt.Color(255, 255, 255));
    applicationPanel.setPreferredSize(new java.awt.Dimension(600, 400));

    applyLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    applyLabel.setForeground(new java.awt.Color(22, 22, 22));
    applyLabel.setText("Order new product");

    applyButton.setText("solicitar");
    applyButton.setActionCommand("Order");
    applyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        applyButtonActionPerformed(evt);
      }
    });

    title1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    title1.setForeground(new java.awt.Color(22, 22, 22));
    title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title1.setText("credit card");

    javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
    applicationPanel.setLayout(applicationPanelLayout);
    applicationPanelLayout.setHorizontalGroup(
      applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(applicationPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        .addGap(20, 20, 20))
      .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(applicationPanelLayout.createSequentialGroup()
          .addGap(200, 200, 200)
          .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(applyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addContainerGap(200, Short.MAX_VALUE)))
    );
    applicationPanelLayout.setVerticalGroup(
      applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(applicationPanelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(323, Short.MAX_VALUE))
      .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(applicationPanelLayout.createSequentialGroup()
          .addGap(156, 156, 156)
          .addComponent(applyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(161, Short.MAX_VALUE)))
    );

    tabbedPane.addTab("application", applicationPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabbedPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
      String response = service.creditCardApplication();
      JOptionPane.showMessageDialog(this, response, "Información", JOptionPane.INFORMATION_MESSAGE);
      enableApplyButton();
      refreshData();
      fillComboBox();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
      service.logOut();
      container.showLoginPanel();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void selectedCreditCardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectedCreditCardItemStateChanged
      onComboBoxChange();
    }//GEN-LAST:event_selectedCreditCardItemStateChanged

    private void savePurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePurchaseButtonActionPerformed
      try {
        LocalDate fecha = LocalDate.parse(purchaseDateField.getText(), DATE_FORMAT);
        Double precio = Double.valueOf(purchasePriceField.getText());
        String descripcion = purchaseTextArea.getText();

        if (descripcion.isEmpty()) {
          JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
          return;
        }

        String response = service.registerPurchase(fecha, descripcion, precio);
        JOptionPane.showMessageDialog(this, response, "Información", JOptionPane.INFORMATION_MESSAGE);

      } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un precio válido.", "Error", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_savePurchaseButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
      try {
//            LocalDate fecha = LocalDate.parse(paymentDateField.getText(), DATE_FORMAT);
        Double monto = Double.valueOf(paymentPriceField.getText());
        String response = service.registerPayment(monto);
        JOptionPane.showMessageDialog(this, response, "Información", JOptionPane.INFORMATION_MESSAGE);

      } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_paymentButtonActionPerformed

  private void transactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsButtonActionPerformed
    try {

      String endDateText = transactionsEndDateField.getText();
      LocalDate endDate = LocalDate.parse(endDateText, DATE_FORMAT);

      String startDateText = transactionsStartDateField.getText();
      LocalDate startDate = LocalDate.parse(startDateText, DATE_FORMAT);

      if (startDate.isAfter(endDate)) {
        JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser mayor que la fecha de fin.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
      }

      List<Transaction> transactions = service.getTransactionByDate(startDate, endDate);

      if (transactions.isEmpty()) {
        transactionsTextArea.setText("No hay movimientos en este período.");
      }
      StringBuilder sb = new StringBuilder();
      for (Transaction t : transactions) {
        sb.append("Fecha: ").append(t.getDate()).append(" | ")
                .append("Descripción: ").append(t.getDescription()).append(" | ")
                .append("Monto: ").append(t.getAmount()).append("\n");
      }
      transactionsTextArea.setText(sb.toString());

    } catch (DateTimeParseException e) {
      JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_transactionsButtonActionPerformed

  public void init() {
    clearFileds();
    refreshData();
    fillComboBox();
    enableApplyButton();
  }

  private void clearFileds() {
    debtField.setText("0");
    quotaField.setText("0");
    applyButton.setEnabled(Boolean.TRUE);
    selectedCreditCard.setEnabled(Boolean.TRUE);
  }

  private void refreshData() {
    service.account();
  }

  private void fillComboBox() {

    selectedCreditCard.removeAllItems();
    var cards = service.getCreditCards();

    if (cards.isEmpty()) {
      selectedCreditCard.setEnabled(Boolean.FALSE);
      return;
    }

    cards.forEach(card -> {
      selectedCreditCard.addItem(card.getNumber());
    });

    selectedCreditCard.setEnabled(Boolean.TRUE);

  }

  private void enableApplyButton() {

    var cards = service.getCreditCards();
    Boolean isEnable = cards.isEmpty() || cards.size() < 3;
    applyButton.setEnabled(isEnable);

  }

  private void onComboBoxChange() {

    var numberCard = selectedCreditCard.getSelectedItem();

    if (numberCard == null) {
      return;
    }

    service.setSelectedCreditCard(numberCard.toString());

    var card = service.getCreditCard();
    quotaField.setText(card.getBalance().toString());
    debtField.setText(card.getDebt().toString());

  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel applicationPanel;
  private javax.swing.JButton applyButton;
  private javax.swing.JLabel applyLabel;
  private javax.swing.JLabel ccLabel5;
  private javax.swing.JLabel debtField;
  private javax.swing.JLabel debtLabel;
  private javax.swing.JPanel info;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton logOutButton;
  private javax.swing.JButton paymentButton;
  private javax.swing.JTextField paymentDateField;
  private javax.swing.JLabel paymentDateLabel;
  private javax.swing.JTextField paymentPriceField;
  private javax.swing.JLabel paymentPriceLabel;
  private javax.swing.JPanel paymentsPanel;
  private javax.swing.JTextField purchaseDateField;
  private javax.swing.JLabel purchaseDateLabel;
  private javax.swing.JLabel purchaseDescriptionLabel;
  private javax.swing.JTextField purchasePriceField;
  private javax.swing.JLabel purchasePriceLabel;
  private javax.swing.JTextArea purchaseTextArea;
  private javax.swing.JPanel purchasesPanel;
  private javax.swing.JLabel quotaField;
  private javax.swing.JLabel quotaLabel;
  private javax.swing.JButton savePurchaseButton;
  private javax.swing.JComboBox<String> selectedCreditCard;
  private javax.swing.JTabbedPane tabbedPane;
  private javax.swing.JLabel title;
  private javax.swing.JLabel title1;
  private javax.swing.JLabel title2;
  private javax.swing.JLabel title3;
  private javax.swing.JLabel title4;
  private javax.swing.JButton transactionsButton;
  private javax.swing.JTextField transactionsEndDateField;
  private javax.swing.JLabel transactionsEndDateLabel;
  private javax.swing.JPanel transactionsPanel;
  private javax.swing.JTextField transactionsStartDateField;
  private javax.swing.JLabel transactionsStartDateLabel;
  private javax.swing.JTextArea transactionsTextArea;
  // End of variables declaration//GEN-END:variables

}
